export const BLUE = '#74c2ec'
export const LIGHT_BLUE = '#d5edf9'
export const LIGHTEST_BLUE = '#f7fcfe'
export const BG_BLUE = '#47aee6'
export const DARK_BLUE = '#31a4e3'
export const WHITE = '#FFFF'
export const DARK_TEXT = '#53585b'
